[tool.poetry]
name = "pong-rl"
version = "0.1.0"
description = ""
authors = ["Nemanja Micovic <nemanjam@nordeus.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyxel = "^1.2.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
